# Myridius 2026 rows 2-21 of the online copy of Details_SkillAssist.xlsx (Google Sheets, 2026-10-05): a new block dated
# 16-07-2026 placed above the old rows (old rows 23+ = the 39 items loaded by myr.py). Same rules as myr.py: track = LP
# Name (blank = merged cell, continues the LP above; Course Name likewise), course "Milestone (Assessment) N" ->
# Milestone Assessment N else Assignment, CSM "Internal Request", topic = skill_name in "(Added manually) / Myridius
# skills" (new skills Programming Fundamentals, SQL, MySQL appended), assessment_name / course_name kept in extra.
import json, re, sys
CLIENT, CSM, FN, SH, DATE = 'Myridius', 'Internal Request', '(Added manually)', 'Myridius skills', '2026-07-16'
SRC = 'Details_SkillAssist.xlsx (online copy, Google Sheets)'
JM, MB = 'Java 21 Programming Masterclass: Fundamentals for Beginners', 'The Complete MySQL from Scratch: Bootcamp'
JR, DE, AA = 'Java Jr Developer_L1', 'Data Engineer_L2', 'Associate Automation Engineer_L1'
ROWS = [  # (row, LP or None, course or None, assessment_name, skill, SkillAssist name)
    (2, JR, JM, 'Assignment_Sort Array', 'Programming Fundamentals', 'Java - Sort Array'),
    (3, None, None, 'Secure Data Handler', 'Programming Fundamentals', 'Java - Secure Data Handler'),
    (4, DE, 'Milestone Assessment 2', 'Evaluation of Postfix Expressions', 'Programming Fundamentals', 'Python - Evaluation of Postfix Expressions'),
    (5, None, None, 'Secure Data Handler', 'Programming Fundamentals', 'Python - Secure Data Handler'),
    (6, JR, JM, 'Assignment_Virtual Paint', 'Programming Fundamentals', 'Java - Virtual Paint Application'),
    (7, AA, 'Milestone 3', 'Total Revenue Generated by Customers', 'SQL', 'SQL - Total Revenue Generated by Customers'),
    (8, JR, JM, 'Assignment_Second Largest Number', 'Programming Fundamentals', 'Java - Second Largest Number'),
    (9, JR, MB, 'Assignment_Extract First 5 Characters from Service Ticket Descriptions', 'SQL', 'SQL - Extract First 5 Characters from Service Ticket Descriptions'),
    (10, None, None, 'Browser History Navigation', 'Programming Fundamentals', 'Java - Browser History Navigation'),
    (11, DE, 'Milestone Assessment 1', 'Show the total number of employees who joined each year', 'MySQL', 'SQL - Show the total number of employees who joined each year'),
    (12, AA, 'Milestone 3', 'Employees from Department d007', 'MySQL', 'SQL - Employees from Department d007'),
    (13, JR, MB, "Assignment_Display all network towers and any associated maintenance records from 'Towers' and 'MaintenanceLogs' including towers without maintenance records", 'SQL',
     "SQL - Display all network towers and any associated maintenance records from 'Towers' and 'MaintenanceLogs' including towers without maintenance records"),
    (14, None, None, 'Weird-Sum', 'Programming Fundamentals', 'Java - Weird-Sum'),
    (15, JR, MB, 'Assignment_List Shipments for the December Month, Sorted by the Total quantity shipped by carrier in Ascending Order', 'SQL',
     'SQL - List Shipments for the December Month, Sorted by the Total quantity shipped by carrier in Ascending Order'),
    (16, DE, 'Milestone Assessment 1', 'Find out which patients are scheduled for surgery and the surgeons assigned to them', 'SQL',
     'SQL - Find out which patients are scheduled for surgery and the surgeons assigned to them'),
    (17, JR, JM, 'Assignment_Camel Case', 'Programming Fundamentals', 'Java - Camel Case'),
    (18, None, None, 'Employees from Department d007', 'MySQL', 'SQL - Employees from Department d007'),
    (19, JR, MB, 'Assignment_Identify Shipments Exceeding Expected Delivery Window for each Destination', 'SQL',
     'SQL - Identify Shipments Exceeding Expected Delivery Window for each Destination'),
    (20, DE, 'Milestone Assessment 1', 'Extract a specific set of characters from tracking IDs for a security check', 'SQL',
     'SQL - Extract a specific set of characters from tracking IDs for a security check'),
    (21, DE, 'Milestone Assessment 2', 'Movie Library Management System', 'Programming Fundamentals', 'Python - Movie Library Management System'),
]
NEW_SKILLS = [(15, 'Programming Fundamentals'), (16, 'SQL'), (17, 'MySQL')]
items, lp, course = [], None, None
for r, l, c, an, sk, name in ROWS:
    lp, course = l or lp, c or course
    m = re.search(r'milestone(?: assessment)?\s*(\d+)', course, re.I)
    typ, seq = ('Milestone Assessment', m.group(1)) if m else ('Assignment', None)
    items.append(dict(row=r, track=lp, typ=typ, seq=seq, name=name, skill=sk,
                      extra={'assessment_name': an, 'course_name': course, 'source': {'file': SRC, 'sheet': 'Myridius 2026', 'row': r}}))
    print(r, lp, typ, seq or '', name[:50], f'[{sk}]', file=sys.stderr)

q = lambda o: '$j$' + json.dumps(o, ensure_ascii=False) + '$j$'
t = lambda s: 'null' if s is None else '$n$' + s + '$n$'
out = ['begin;', f"""insert into toc_rows(toc_file_id,row_number,day_label,topic,data)
select f.id,x.row_number,null,x.topic,x.data from toc_files f join clients c on c.id=f.client_id and c.name={t(CLIENT)},
 jsonb_to_recordset({q([dict(row_number=n, topic=s, data={'Topic': s}) for n, s in NEW_SKILLS])}::jsonb) as x(row_number int, topic text, data jsonb)
where f.file_name={t(FN)} and f.sheet_name={t(SH)} on conflict (toc_file_id,row_number) do update set topic=excluded.topic, data=excluded.data;"""]
for tr in dict.fromkeys(i['track'] for i in items):
    out.append(f"insert into tracks(client_id,name,csm) select id,{t(tr)},{t(CSM)} from clients where name={t(CLIENT)} on conflict (client_id,name) do nothing;")
for i in items:
    out.append(f"""with ctx as (select c.id cid, tr.id tid, f.id fid from clients c join tracks tr on tr.client_id=c.id and tr.name={t(i['track'])} join toc_files f on f.client_id=c.id and f.file_name={t(FN)} and f.sheet_name={t(SH)} where c.name={t(CLIENT)}),
ins as (insert into contents(client_id,track_id,content_type,sequence_label,name,delivery_date,extra)
 select cid,tid,{t(i['typ'])},{t(i['seq'])},{t(i['name'])},'{DATE}',{q(i['extra'])}::jsonb from ctx
 on conflict (client_id,track_id,content_type,sequence_label,name) do update set delivery_date=excluded.delivery_date, extra=excluded.extra returning id)
insert into content_toc_links(content_id,toc_row_id)
select ins.id,r.id from ins cross join ctx join toc_rows r on r.toc_file_id=ctx.fid and r.topic={t(i['skill'])} on conflict do nothing;""")
out.append('commit;')
print(len(items), 'items', file=sys.stderr)
print('\n'.join(out))
